[general]
working_directory = "C:/Users/ltumi"
# import = ["themes/kanagawa_wave.toml"]
# import = ["themes/tokyo_night.toml"]
import = ["themes/blood_moon.toml"]
# import = ["themes/gruber_darker.toml"]

[window]
dimensions = { columns = 110, lines = 27 }
position = "None"
startup_mode = "Windowed"
decorations = "Full"
opacity = 1.0
padding = { x = 20, y = 0 }
dynamic_padding = true
title = ""
dynamic_title = false

[scrolling]
history = 5000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[cursor]
style = { shape = "Beam", blinking = "On" }

[terminal]
shell = { program = "pwsh.exe", args = ["-NoLogo"] }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true
