[general]
working_directory = "C:/Users/ltumi"
import = ["themes/blood_moon.toml"]
# import = ["themes/gruber_darker.toml"]

[window]
dimensions = { columns = 110, lines = 27 }
position = "None"
startup_mode = "Windowed"
decorations = "Full"
opacity = 1.0
padding = { x = 20, y = 0 }
dynamic_padding = true
title = ""
dynamic_title = false

[scrolling]
history = 5000

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
size = 14.0

[cursor]
style = { shape = "Block", blinking = "On" }

[terminal]
shell = { program = "pwsh.exe", args = ["-NoLogo"] }

[selection]
save_to_clipboard = true

[mouse]
hide_when_typing = true

[colors.cursor]
text = "#1F1F28"
cursor = "#DCD7BA"

[colors.selection]
text = "#DCD7BA"
background = "#2A2A37"

# Colors: Tokyonight
# [colors.bright]
# black = "#444b6a"
# blue = "#7da6ff"
# cyan = "#0db9d7"
# green = "#b9f27c"
# magenta = "#bb9af7"
# red = "#ff7a93"
# white = "#acb0d0"
# yellow = "#ff9e64"
#
# [colors.normal]
# black = "#32344a"
# blue = "#7aa2f7"
# cyan = "#449dab"
# green = "#9ece6a"
# magenta = "#ad8ee6"
# red = "#f7768e"
# white = "#9699a8"
# yellow = "#e0af68"
#
# [colors.primary]
# background = "#222436"
# foreground = "#a9b1d6"

# Colors: Kanagawa
# [colors.primary]
# background = "#1F1F28"
# foreground = "#DCD7BA"
#
# [colors.normal]
# black   = "#1F1F28"
# red     = "#E82424"
# green   = "#76946A"
# yellow  = "#FF9E3B"
# blue    = "#658594"
# magenta = "#957FB8"
# cyan    = "#9CABCA"
# white   = "#DCD7BA"
#
# [colors.bright]
# black   = "#8181A9"
# red     = "#FF5D62"
# green   = "#98BB6C"
# yellow  = "#E6C384"
# blue    = "#7FB4CA"
# magenta = "#D27E99"
# cyan    = "#A3D4D5"
# white   = "#DCD7BA"
